
# Name workflow
name: Pull request

# Triggers the workflow on push or pull request.
on:

  # Trigger push request.
  push:
    branches: [ develop ]

  # Trigger pull request.
  pull_request:
    branches: [ develop ]

# List jobs, can run sequentially or in parallel
jobs:

  # Job 1
  test:
    name: Run Unit Tests  # Job name
    runs-on: ubuntu-latest  # Environment Runner run Job 1.
    # or windows-latest, macos-latest

    # List steps, list actions
    steps:

      # Action 1  # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout # Name action 1
        uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Build with gragle
        run: bash ./gradlew build --stacktrace

      - name: Unit Tests Results
        uses: actions/upload-artifact@v2
        with:
          name: unit-tests-results
          path: app/build/reports/tests/testDebugUnitTest/index.html

  apk:
    name: Generate APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Build debug APK
        run: bash ./gradlew assembleDebug --stacktrace

      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: app
          path: app/build/outputs/apk/debug/app-debug.apk

